<a href="https://colab.research.google.com/github/nhi-02/PyTorchww/blob/main/zero_PyTorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **zero: PyTorch fundamentals**

In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.6.0+cu124


In [ ]:
!nvidia-smi

Fri Jul 25 08:08:44 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   53C    P8             12W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

# Tensor


In [ ]:
# scalar
scalar = torch.tensor(2)
scalar

tensor(2)

In [ ]:
scalar.ndim

0

In [ ]:
# get tensor back as Python init
scalar.item()

2

In [ ]:
# vector
vector = torch.tensor([1, 2])
vector

tensor([1, 2])

In [ ]:
vector.ndim

1

In [ ]:
# matrix
matrix = torch.tensor([[1, 2], [3, 4]])
matrix

tensor([[1, 2],
        [3, 4]])

In [ ]:
matrix.ndim

2

In [ ]:
matrix.shape

torch.Size([2, 2])

In [ ]:
# tensor
tensor = torch.tensor([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
tensor

tensor([[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]]])

In [ ]:
tensor.ndim

3

In [ ]:
tensor.shape

torch.Size([2, 2, 3])

## Random Tensor
- Many neural network learn is that they start with tensors full of random numbers and then they adjust those random numbers to better represent the data.

`Start with random numbers -> look at data -> update random numbers -> look at data -> update rd`



In [ ]:
# Create a random tensor of sizr (3, 4)
random_tensor = torch.rand(3, 4, 2)
random_tensor

tensor([[[0.6462, 0.4723],
         [0.6156, 0.0987],
         [0.7229, 0.7964],
         [0.8571, 0.8759]],

        [[0.9595, 0.6806],
         [0.3079, 0.3846],
         [0.6817, 0.7358],
         [0.3295, 0.0715]],

        [[0.2317, 0.9780],
         [0.2760, 0.1502],
         [0.7183, 0.7299],
         [0.7493, 0.8515]]])

In [ ]:
random_tensor.ndim

3

In [ ]:
# Create a random tensor with simalar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224, 224, 3)) # height, width, color channels (R, G, B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [ ]:
# Create tensor of all zeros/ones
zeros = torch.zeros(size=(3, 4))
ones = torch.ones(size=(3,4))

In [ ]:
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

Creating a range of tensor and tensors-like

In [ ]:
one_to_ten = torch.range(1, 11)
one_to_ten

/tmp/ipython-input-20-3025000668.py:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  one_to_ten = torch.range(1, 11)


tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [ ]:
jumpy_tensor = torch.arange(start=0, end=1000, step=77)
jumpy_tensor

tensor([  0,  77, 154, 231, 308, 385, 462, 539, 616, 693, 770, 847, 924])

In [ ]:
# Creating tensors like (same shape)
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

## Tensor datatypes

In [ ]:
# float 32 tensor
float_32_tensor = torch.tensor([1.0, 2.0, 3.0], dtype=None, # what datatype is the tensor (None = float 32)
                                                device=None, # what device is tensor on (None = cpu) (if gpu -> 'cuda')
                                                requires_grad=False # whether or not to track gradients with this tensors operations
                                                )
float_32_tensor.dtype

torch.float32

In [ ]:
float_32_tensor.dtype

torch.float32

## Getting information from tensors

In [ ]:
tensors = torch.rand(3, 4)
tensors

tensor([[0.4328, 0.5692, 0.0435, 0.7064],
        [0.4885, 0.1043, 0.5131, 0.4374],
        [0.2654, 0.0173, 0.9727, 0.4495]])

In [ ]:
# datatype
tensors.dtype

torch.float32

In [ ]:
# shape
tensors.shape

torch.Size([3, 4])

In [ ]:
# device\
tensors.device

device(type='cpu')

## Manipulating tensors (tensor operations)/ thao tac voi tensor

* Addition
* Subtraction
* Multiplication (element wise/nhan phan tu tuong ung)
* Division
* Matrix multiplication

In [ ]:
tensor = torch.tensor([1, 2, 3])
# add
tensor + 10

tensor([11, 12, 13])

In [ ]:
# multipl
tensor * 10

tensor([10, 20, 30])

In [ ]:
# sub
tensor - 10

tensor([-9, -8, -7])

In [ ]:
# PyTorch in-built func
torch.mul(tensor, 10)

tensor([10, 20, 30])

### Matrix multiplication (dot product)

In [ ]:
# Dot product
print(tensor)
print(torch.matmul(tensor, tensor))

tensor([1, 2, 3])
tensor(14)


In [ ]:
tensor1 = torch.rand(3, 4)
tensor1

tensor([[0.8620, 0.8222, 0.5082, 0.7719],
        [0.9306, 0.0992, 0.0682, 0.4576],
        [0.7372, 0.4503, 0.9777, 0.5225]])

In [ ]:
tensor2 = torch.rand(4, 3)
tensor2

tensor([[0.0091, 0.8241, 0.7318],
        [0.6832, 0.6491, 0.0807],
        [0.7812, 0.6655, 0.7014],
        [0.1250, 0.3052, 0.9954]])

In [ ]:
torch.matmul(tensor2, tensor1)

tensor([[1.3142, 0.4187, 0.7763, 0.7665],
        [1.2524, 0.6624, 0.4703, 0.8665],
        [1.8097, 1.0242, 1.1281, 1.2739],
        [1.1255, 0.5813, 1.0575, 0.7562]])

In [ ]:
torch.matmul(tensor1, tensor2)

tensor([[1.0630, 1.8178, 1.8219],
        [0.1866, 1.0164, 1.1924],
        [1.1434, 1.7099, 1.7815]])

In [ ]:
# should using torch funtion for loop
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: user 359 µs, sys: 891 µs, total: 1.25 ms
Wall time: 1.06 ms


In [ ]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 37 µs, sys: 0 ns, total: 37 µs
Wall time: 39.6 µs


tensor(14)

**Số cột của tensor** này phải tương ứng với số hàng của tensor kia
Tensor matrix 1 . tensor matrix 2 khác tensor matrix 2 . tensor matrix 1

`(3, 4) . (4, 3)` -> `(3, 3)`

`(4, 3) . (3, 4)` -> `(4, 4)`

In [ ]:
tensorA = torch.tensor([[1, 2], [3, 4], [5, 6]])
tensorB = torch.tensor([[7, 10], [8, 11], [9, 12]])
tensorA.shape, tensorB.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

In [ ]:
torch.mm(tensorA, tensorB) # torch.mm = torch.matmul

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

To fix out tensor shape error -> **transpose** = switches the axes or dimension of a given tensor.

In [ ]:
tensorB.T

tensor([[ 7,  8,  9],
        [10, 11, 12]])

In [ ]:
torch.mm(tensorA, tensorB.T)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

### Finding the min, max, mean, sum, etc (tensor aggregation)

In [ ]:
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
torch.min(x), x.min()

(tensor(0), tensor(0))

In [ ]:
torch.max(x), x.max()

(tensor(90), tensor(90))

In [ ]:
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()
# torch.mean() requires a tensor of float32 to work

(tensor(45.), tensor(45.))

In [ ]:
torch.sum(x), x.sum()

(tensor(450), tensor(450))

### Finding the postional min and max

In [ ]:
x.argmin() # index where minimum value

tensor(0)

In [ ]:
x.argmax()

tensor(9)

### Reshaping, stacking, squeezing and unsqueezing tensors

In [ ]:
import torch
x = torch.arange(1., 11.)
x, x.shape

(tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]), torch.Size([10]))

In [ ]:
# Add an extradimension
x_reshaped = x.reshape(2, 5) # so phan tu khong thay doi, chi thay doi shape 2 x 5 = 10
x_reshaped, x_reshaped.shape

(tensor([[ 1.,  2.,  3.,  4.,  5.],
         [ 6.,  7.,  8.,  9., 10.]]),
 torch.Size([2, 5]))

In [ ]:
# Change the view
z = x.view(2, 5)
z, z.shape

(tensor([[ 1.,  2.,  3.,  4.,  5.],
         [ 6.,  7.,  8.,  9., 10.]]),
 torch.Size([2, 5]))

In [ ]:
z[:, 0] = 2
z, x

(tensor([[ 2.,  2.,  3.,  4.,  5.],
         [ 2.,  7.,  8.,  9., 10.]]),
 tensor([ 2.,  2.,  3.,  4.,  5.,  2.,  7.,  8.,  9., 10.]))

In [ ]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim = 1)
x_stacked

tensor([[ 2.,  2.,  2.,  2.],
        [ 2.,  2.,  2.,  2.],
        [ 3.,  3.,  3.,  3.],
        [ 4.,  4.,  4.,  4.],
        [ 5.,  5.,  5.,  5.],
        [ 2.,  2.,  2.,  2.],
        [ 7.,  7.,  7.,  7.],
        [ 8.,  8.,  8.,  8.],
        [ 9.,  9.,  9.,  9.],
        [10., 10., 10., 10.]])

In [ ]:
# Squeeze
x_reshaped.shape, x_reshaped.squeeze().shape

(torch.Size([2, 5]), torch.Size([2, 5]))

In [ ]:
# Unsqueeze - add a single dimension
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

# Add an extra dimension with unsqueeze
x_unsqueezed = x_reshaped.unsqueeze(dim=2)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")


Previous tensor: tensor([[ 2.,  2.,  3.,  4.,  5.],
        [ 2.,  7.,  8.,  9., 10.]])
Previous shape: torch.Size([2, 5])

New tensor: tensor([[[ 2.],
         [ 2.],
         [ 3.],
         [ 4.],
         [ 5.]],

        [[ 2.],
         [ 7.],
         [ 8.],
         [ 9.],
         [10.]]])
New shape: torch.Size([2, 5, 1])


In [ ]:
# Permute - hoan doi thu tu cac chieu dimension ma khong thay doi du lieu ben trong
x_original = torch.rand(size=(224, 224, 3)) # height, width, color channels

# ---
x_permuted = x_original.permute(2, 0, 1) # shift axis 0->1, 1->2, 2->0  / color channels, height, width

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}")

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


## Indexing (slecting data from tensor)

In [ ]:
import torch
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [ ]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
x[0][0], x[0, 0]

(tensor([1, 2, 3]), tensor([1, 2, 3]))

In [ ]:
x[0][0][0], x[0, 0, 0]

(tensor(1), tensor(1))

In [ ]:
# use : to select 'all' of target dimension
x[:, 0]

tensor([[1, 2, 3]])

In [ ]:
x[:, :, 0]

tensor([[1, 4, 7]])

## PyTorch tensors and Numpy
* Data in Numpy, want in PyTorch tensor -> `torch.from_numpy(ndarray)`
* PyTorch tensor -> Numpy `torch.Tensor.numpy()`

In [ ]:
# Numpy array to tensor
import torch
import numpy as np

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
# Change value of array, tensor doesnt change value
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
# Tensor to Numpy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [ ]:
# Change the tensor, numpy array also doesnt change
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducbility ( try to take random out of random)
To reduce the randomness in neural networks anf PyTorch comes the concept of a random seed

To make sure that your code gives the same results every time it run. This is important for debugging, comparing models, or scientific experiments.

Essentially what the random seed does is "flavour" the randomness

In [ ]:
import torch
# Create two random tensor
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.1445, 0.7432, 0.7293, 0.6995],
        [0.3712, 0.8580, 0.4315, 0.3731],
        [0.1143, 0.0780, 0.5811, 0.1148]])
tensor([[0.3921, 0.4617, 0.0088, 0.6013],
        [0.5071, 0.7808, 0.5677, 0.0769],
        [0.6094, 0.7723, 0.6664, 0.7607]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [ ]:
# Random but reproducible tensor
import torch
# Set the random seed
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3, 4)

torch.manual_seed(RANDOM_SEED) # generally it works for only on block of code if youre using a notebook
random_tensor_D = torch.rand(3, 4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## Running tensor and PyTorch objects on the GPUs (and making faster computations)


### Getting a GPU
1. Use GG Colab free
2. Use your own GPU
3. Use cloud computing - GCP, AWS, Azure


In [ ]:
!nvidia-smi

Fri Jul 25 14:38:16 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   42C    P8              9W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

### Checking for GPU access with PyTorch

In [ ]:
# Check for GPU
import torch
torch.cuda.is_available()

True

In [ ]:
# Setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [ ]:
# Count number of devices
torch.cuda.device_count()

1

### Putting tensors (and models) on GPU)


In [ ]:
import torch
# Create a tensor (default on the CPU)
tensor = torch.tensor([1, 2, 3])

tensor.device

device(type='cpu')

In [ ]:
# Move tensor to GPU
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

### Moving tensors back to the CPU

In [ ]:
# If tensor is on GPU, cant transform it to Numpy
tensor_on_gpu.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [ ]:
# Fix
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])

## Exercise & Extra-curiculum

In [ ]:
# Create random tensor with shape (7, 7)
tensor = torch.rand(7, 7)
tensor, tensor.shape

(tensor([[0.2360, 0.8282, 0.1870, 0.7107, 0.4399, 0.5260, 0.9954],
         [0.3752, 0.1117, 0.4093, 0.7594, 0.3758, 0.4758, 0.5952],
         [0.4775, 0.8457, 0.0414, 0.2809, 0.2716, 0.9822, 0.7997],
         [0.7333, 0.5614, 0.4789, 0.6654, 0.8500, 0.9462, 0.4218],
         [0.7511, 0.0567, 0.4568, 0.2901, 0.4891, 0.2825, 0.4440],
         [0.5564, 0.6627, 0.9597, 0.8445, 0.5621, 0.9325, 0.4195],
         [0.3480, 0.4418, 0.6477, 0.6138, 0.8930, 0.8258, 0.6940]]),
 torch.Size([7, 7]))

In [ ]:
# Matrix multiplication 2 random tensor with shape (1, 7)
tensor1 = torch.rand(1, 7)
tensor2 = torch.rand(1, 7)

tensor1, tensor2, tensor2.T, torch.matmul(tensor1, tensor2.T)

(tensor([[0.9313, 0.0963, 0.3194, 0.4817, 0.1923, 0.2424, 0.0306]]),
 tensor([[0.2268, 0.3136, 0.2431, 0.9045, 0.4584, 0.1570, 0.4612]]),
 tensor([[0.2268],
         [0.3136],
         [0.2431],
         [0.9045],
         [0.4584],
         [0.1570],
         [0.4612]]),
 tensor([[0.8951]]))

In [ ]:
# Set the random seed equal 0 and do again
RANDOM_SEED = 0
torch.manual_seed(RANDOM_SEED)
tensor = torch.rand(7, 7)

torch.manual_seed(RANDOM_SEED)
tensor1 = torch.rand(1, 7)

torch.manual_seed(RANDOM_SEED)
tensor2 = torch.rand(1, 7)

tensor, tensor1, tensor2, torch.matmul(tensor1, tensor2.T)

(tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901],
         [0.8964, 0.4556, 0.6323, 0.3489, 0.4017, 0.0223, 0.1689],
         [0.2939, 0.5185, 0.6977, 0.8000, 0.1610, 0.2823, 0.6816],
         [0.9152, 0.3971, 0.8742, 0.4194, 0.5529, 0.9527, 0.0362],
         [0.1852, 0.3734, 0.3051, 0.9320, 0.1759, 0.2698, 0.1507],
         [0.0317, 0.2081, 0.9298, 0.7231, 0.7423, 0.5263, 0.2437],
         [0.5846, 0.0332, 0.1387, 0.2422, 0.8155, 0.7932, 0.2783]]),
 tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901]]),
 tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901]]),
 tensor([[1.5985]]))

In [ ]:
# Random seed on GPU
RANDOM_SEED = 1234
torch.cuda.manual_seed(RANDOM_SEED)
tensor = torch.rand(2, 3, device = device)

tensor, tensor.device

(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]]),
 device(type='cpu'))

In [ ]:
# Two random tensors of shape (2, 3) on GPU
RANDOM_SEED = 1234
torch.cuda.manual_seed(RANDOM_SEED)

tensor3 = torch.rand(2, 3, device = device)
tensor4 = torch.rand(2, 3, device = device)

tensor3, tensor4

(tensor([[0.1272, 0.8167, 0.5440],
         [0.6601, 0.2721, 0.9737]], device='cuda:0'),
 tensor([[0.6208, 0.0276, 0.3255],
         [0.1114, 0.6812, 0.3608]], device='cuda:0'))

In [ ]:
# Matrix multiplicaton
tensor5 = torch.matmul(tensor3.T, tensor4)
tensor5

tensor([[0.1525, 0.4531, 0.2796],
        [0.5374, 0.2079, 0.3640],
        [0.4462, 0.6783, 0.5284]], device='cuda:0')

In [ ]:
tensor5.max()

tensor(0.6783, device='cuda:0')

In [ ]:
tensor5.min()

tensor(0.1525, device='cuda:0')

In [ ]:
tensor5.argmax()

tensor(7, device='cuda:0')

In [ ]:
tensor5.argmin(), torch.argmin(tensor5)

(tensor(0, device='cuda:0'), tensor(0, device='cuda:0'))

In [ ]:
# Create tensors with shape (1, 1, 1, 10) and random seed = 7.
# Then all the 1 dimension removed -> tensor of shape 10
random_seed = 7
torch.manual_seed(random_seed)
tensor6 = torch.rand(1, 1, 1, 10)

tensor7 = tensor6.squeeze(dim = 1)
tensor6, tensor6.shape, tensor7, tensor7.shape

(tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
            0.3653, 0.8513]]]]),
 torch.Size([1, 1, 1, 10]),
 tensor([[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]),
 torch.Size([1, 1, 10]))